name: "Cache Sandbox Runner"
on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Generate file
        run: |
          echo "Hello World!" > message.txt
          cat message.txt

      - name: Save file to cache
        uses: actions/cache/save@v4
        with:
          path: message.txt
          key: MESSAGE
