name: "Cache Sandbox Runner"
on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Generate file
        run: |
          echo "Hello World!" > message
          cat message
